---
version: 2

project_name: url2anki

env:
  - GO111MODULE=on

env_files:
  gitlab_token: ~/nope
  gitea_token: ~/nope

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

snapshot:
  version_template: '{{ incpatch .Version }}-next'

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate
        }} -X main.builtBy=goreleaser
    main: ./
    binary: url2anki

universal_binaries:
  - replace: false

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

dockers:
  - image_templates:
      - 'toozej/url2anki:{{ .Tag }}-amd64'
      - 'ghcr.io/toozej/url2anki:{{ .Tag }}-amd64'
      - 'quay.io/toozej/url2anki:{{ .Tag }}-amd64'
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/toozej/url2anki/main/README.md"
      - "--label=io.artifacthub.package.maintainers=[{\"name\":\"toozej\"}]"
      - "--label=io.artifacthub.package.license=GPLv3"
      - "--label=org.opencontainers.image.description=Golang starter template"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    extra_files:
      - scripts/goreleaser_entrypoint.sh
  - image_templates:
      - 'toozej/url2anki:{{ .Tag }}-arm64'
      - 'ghcr.io/toozej/url2anki:{{ .Tag }}-arm64'
      - 'quay.io/toozej/url2anki:{{ .Tag }}-arm64'
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/toozej/url2anki/main/README.md"
      - "--label=io.artifacthub.package.maintainers=[{\"name\":\"toozej\"}]"
      - "--label=io.artifacthub.package.license=GPLv3"
      - "--label=org.opencontainers.image.description=Golang starter template"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64
    extra_files:
      - scripts/goreleaser_entrypoint.sh
  - image_templates:
      - 'toozej/url2anki:{{ .Tag }}-distroless-amd64'
      - 'ghcr.io/toozej/url2anki:{{ .Tag }}-distroless-amd64'
      - 'quay.io/toozej/url2anki:{{ .Tag }}-distroless-amd64'
    dockerfile: Dockerfile.goreleaser.distroless
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/toozej/url2anki/main/README.md"
      - "--label=io.artifacthub.package.maintainers=[{\"name\":\"toozej\"}]"
      - "--label=io.artifacthub.package.license=GPLv3"
      - "--label=org.opencontainers.image.description=Golang starter template"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    extra_files:
      - scripts/goreleaser_entrypoint.sh
  - image_templates:
      - 'toozej/url2anki:{{ .Tag }}-distroless-arm64'
      - 'ghcr.io/toozej/url2anki:{{ .Tag }}-distroless-arm64'
      - 'quay.io/toozej/url2anki:{{ .Tag }}-distroless-arm64'
    dockerfile: Dockerfile.goreleaser.distroless
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/toozej/url2anki/main/README.md"
      - "--label=io.artifacthub.package.maintainers=[{\"name\":\"toozej\"}]"
      - "--label=io.artifacthub.package.license=GPLv3"
      - "--label=org.opencontainers.image.description=Golang starter template"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64
    extra_files:
      - scripts/goreleaser_entrypoint.sh

docker_manifests:
  # tagged
  - name_template: 'toozej/url2anki:{{ .Tag }}'
    image_templates:
      - 'toozej/url2anki:{{ .Tag }}-amd64'
      - 'toozej/url2anki:{{ .Tag }}-arm64'
  - name_template: 'ghcr.io/toozej/url2anki:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/toozej/url2anki:{{ .Tag }}-amd64'
      - 'ghcr.io/toozej/url2anki:{{ .Tag }}-arm64'
  - name_template: 'quay.io/toozej/url2anki:{{ .Tag }}'
    image_templates:
      - 'quay.io/toozej/url2anki:{{ .Tag }}-amd64'
      - 'quay.io/toozej/url2anki:{{ .Tag }}-arm64'
  - name_template: 'toozej/url2anki:{{ .Tag }}-distroless'
    image_templates:
      - 'toozej/url2anki:{{ .Tag }}-distroless-amd64'
      - 'toozej/url2anki:{{ .Tag }}-distroless-arm64'
  - name_template: 'ghcr.io/toozej/url2anki:{{ .Tag }}-distroless'
    image_templates:
      - 'ghcr.io/toozej/url2anki:{{ .Tag }}-distroless-amd64'
      - 'ghcr.io/toozej/url2anki:{{ .Tag }}-distroless-arm64'
  - name_template: 'quay.io/toozej/url2anki:{{ .Tag }}-distroless'
    image_templates:
      - 'quay.io/toozej/url2anki:{{ .Tag }}-distroless-amd64'
      - 'quay.io/toozej/url2anki:{{ .Tag }}-distroless-arm64'
  # latest
  - name_template: 'toozej/url2anki:latest'
    image_templates:
      - 'toozej/url2anki:{{ .Tag }}-amd64'
      - 'toozej/url2anki:{{ .Tag }}-arm64'
  - name_template: 'ghcr.io/toozej/url2anki:latest'
    image_templates:
      - 'ghcr.io/toozej/url2anki:{{ .Tag }}-amd64'
      - 'ghcr.io/toozej/url2anki:{{ .Tag }}-arm64'
  - name_template: 'quay.io/toozej/url2anki:latest'
    image_templates:
      - 'quay.io/toozej/url2anki:{{ .Tag }}-amd64'
      - 'quay.io/toozej/url2anki:{{ .Tag }}-arm64'
  # distroless
  - name_template: 'toozej/url2anki:distroless'
    image_templates:
      - 'toozej/url2anki:{{ .Tag }}-distroless-amd64'
      - 'toozej/url2anki:{{ .Tag }}-distroless-arm64'
  - name_template: 'ghcr.io/toozej/url2anki:distroless'
    image_templates:
      - 'ghcr.io/toozej/url2anki:{{ .Tag }}-distroless-amd64'
      - 'ghcr.io/toozej/url2anki:{{ .Tag }}-distroless-arm64'
  - name_template: 'quay.io/toozej/url2anki:distroless'
    image_templates:
      - 'quay.io/toozej/url2anki:{{ .Tag }}-distroless-amd64'
      - 'quay.io/toozej/url2anki:{{ .Tag }}-distroless-arm64'

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

nfpms:
  - file_name_template: '{{ .ConventionalFileName }}'
    id: packages
    homepage: https://github.com/toozej/url2anki
    description: |-
      Generate Anki flashcards from a URL
    maintainer: toozej
    license: GPLv3
    vendor: url2anki
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/url2anki.bash
        dst: /usr/share/bash-completion/completions/url2anki
        file_info:
          mode: 0644
      - src: ./completions/url2anki.fish
        dst: /usr/share/fish/completions/url2anki.fish
        file_info:
          mode: 0644
      - src: ./completions/url2anki.zsh
        dst: /usr/share/zsh/vendor-completions/_url2anki
        file_info:
          mode: 0644
      - src: ./manpages/url2anki.1.gz
        dst: /usr/share/man/man1/url2anki.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/url2anki/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - git
    recommends:
      - golang
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    output: true
    args:
      - 'sign-blob'
      - '--key=env://COSIGN_PRIVATE_KEY'
      - '--yes'
      - '--output-signature=${signature}'
      - '${artifact}'
    artifacts: all

docker_signs:
  - cmd: cosign
    artifacts: all
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    output: true
    args:
      - 'sign'
      - '--key=env://COSIGN_PRIVATE_KEY'
      - '--yes'
      - '${artifact}'

milestones:
  - close: true

release:
  footer: |
    **Full Changelog**: https://github.com/toozej/url2anki/compare/{{ .PreviousTag }}...{{ .Tag }}
